export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const DELETE_COMPANY = "EDIT_COMPANY";

export const GET_CONTRIBUTIONS = "GET_CONTRIBUTIONS";
export const ADD_CONTRIBUTION = "ADD_CONTRIBUTION";
export const DELETE_CONTRIBUTION = "DELETE_CONTRIBUTION";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";