export const GET_COMPANIES = "GET_COMPANIES";
export const ADD_COMPANY = "ADD_COMPANY";
export const EDIT_COMPANY = "EDIT_COMPANY";
export const DELETE_COMPANY = "EDIT_COMPANY";

export const ADD_CONTRIBUTION = "ADD_CONTRIBUTION"